report2idea/amplification2idea.py
Category name should be Availability.DDoS not Availibility.DDoS
=> Fixed typo in category name

Makefile.am, configure.ac, link_traffic/Makefile.am, link_traffic/README.md, link_traffic/link_traffic.c, link_traffic/link_traffic_, nemea-modules.spec.in
Created new module for generating statistics for munin. Creates 3 graphs: flows, packets, bytes with tagged links to show traffic on each node.
=> link_traffic module

link_traffic/munin/link_traffic_
Fixed labels and legend for link_traffic graphs
Outgoing packets/flows/bytes will now appear negative
=> link_traffic: munin: graphs readability improved

link_traffic/README.md, proto_traffic/README.md, proto_traffic/proto_traffic.c
Corrected README due to moving modules from Nemea-Framework to Nemea-Modules
=> link_traffic, proto_traffic: README corrected

topn/topn.c, topn/topn.h
Coding style improved for topn/topn.c
Compiles with warning, but works.
=> topn: coding style improved

report2idea/test.sh, report2idea/venom/venom2idea.py
Use reporter configuration in tests and fix venom2idea with relative import
=> Fix reporter config

flowcounter/README.md, flowcounter/flowcounter.c
Few ajdustments to README.
This module has more issues with memory and proper parameters parsing.
=> README updated, closes #3

report2idea/vportscan/vportscan2idea.py
vportscan aggregator now reports block scans, the output is in JSON.
Should be released at the same with detectors and framework.
=> report2idea: vportscan: adapt to new output of aggregator

aggregator/README.md, aggregator/agg_functions.cpp, aggregator/agg_functions.h, aggregator/aggregator.cpp, aggregator/configuration.cpp, aggregator/configuration.h, aggregator/key.cpp, aggregator/key.h, aggregator/output.cpp, aggregator/output.h
Possible static field out of bound write removed.
Time fields (first, last) assign by user forbidden.
Licence terms added to each source file.
=> Module and src files update.

report2idea/amplificationdetector/amplification2idea.py, report2idea/dnstunnel/dnstunnel2idea.py, report2idea/hoststats/hoststats2idea.py
Change requested by Pavel Kácha from Warden community.
=> Changed "dns" to "domain" in idea messages

scalar-aggregator/aggregator.c
- fixed possible memory leaks
- fixed possible segfaults
- added arguments input check (possible division by zero)
- some coding style fixes
=> scalar_aggregator: code refactoring

demux/demux.cpp, mux/Makefile.am, mux/mux.cpp
Returned value checked of trap_ctx_init
=> Mux,Demux: libtrap api bugfix

anonymizer/anonymizer.c, unirecfilter/README.md, unirecfilter/unirecfilter.c, unirecfilter/unirecfilter.h
Closes #22 
- Added better documentation of usage of this module to README.md with examples
- Added code security checks throughout unirecfilter.c
- Documented function used in unirecfilter.c to unirecfilter.h
=> Documentation improvement, usage examples, checking return values in unirecfilter.c + Anonymizer.c bugfix

unirecfilter/README.md, unirecfilter/lib/functions.c, unirecfilter/lib/functions.h, unirecfilter/lib/liburfilter.c, unirecfilter/lib/parser.y, unirecfilter/lib/scanner.l
It is now possible to filter by the subnet.
The example is in the commit message and description should be in README.
Any comments (/patches) or testing will be welcome.
=> Add subnets feature into Urfilter (= unirecfilter)

blooming_history/blooming_history.c, blooming_history/blooming_history_functions.c, blooming_history/blooming_history_functions.h
See [API doc](https://github.com/fkrestan/blooming_history_aggregator/blob/master/README.md#rest-api) for details.
=> blooming_history: Use new API endpoint for bloom filter upload

report2idea/ddos/ddos_detector2idea.py
changelog: Fixed AltNames attribute in ddos_detector2idea.
=> ddos_detector2idea: bugfix convert altname to str from int

logger/logger.c
Logger did not properly terminate when received SIGINT if one of the
receiving threads was blocked on select() or recv() and no data were coming.
=> logger: fixed bug when logger did not terminate

json_dump/README.md, json_replay/README.md
Added a simple readme for json_dump and json_replay modules.
Closes #101
=> README for json_dump and json_replay

report2idea/amplificationdetector/amplification2idea.py
This fixed incompatibility with the IDEA format.
=> Type moved under Node in amplification2idea

report2idea/amplificationdetector/amplification2idea.py, report2idea/blacklist/blacklist2idea.py, report2idea/bruteforce/bruteforce2idea.py, report2idea/ddos/ddos_detector2idea.py, report2idea/dnstunnel/dnstunnel2idea.py, report2idea/haddrscan/haddrscan2idea.py, report2idea/hoststats/hoststats2idea.py, report2idea/minerdetector/minerdetector2idea.py, report2idea/sipbruteforce/sipbf2idea.py, report2idea/test.sh, report2idea/venom/venom2idea.py, report2idea/voipfraud/voipfraud2idea.py, report2idea/vportscan/vportscan2idea.py
Changed names of reporters to be compatible with https://github.com/CESNET/Nemea-Framework/pull/118
=> report2idea: rename reporters

report2idea/config.yml.example
Added namespace into example config.
=> report2idea: updated config.yml.example

merger/merger.c
This PR simplifies merger and replaces openmp with pthread because of OpenWrt build.
=> Pthread version of merger module

proto_traffic/munin/proto_traffic_, proto_traffic/proto_traffic.c
changelog: Extended statistic of proto_traffic by SCTP.
=> proto_traffic: add SCTP statistic

merger/README.md
... to reflect changes in 3aa6069de88ca142b78ae04ad22b698fd3b7f3b7.
=> Update merger readme

logger/logger.c
Simplified logger to a single input interface, -o parameter marked unsupported, as it has currently no influence on the output.
=> logger: removed threading, parameter -o disabled

merger/Makefile.am, merger/merger.c, merger/test/Makefile.am, merger/test/compare_output.sh, merger/test/compare_user_limited_output.sh
The behavior of merger is fixed according to discussion with @qha .
This PR is a replacement of #132. It closes #132.
=> Merger fixed behavior of given output template

aggregator/agg_functions.cpp, aggregator/output.cpp, prefix_tags/prefix_tags_config.c
An (probably unsuccessful) attempt to help with the current situation (discussed off-band).
=> Small fixes for agg & prefix_tags

flow_meter/create_plugin.sh, flow_meter/unirecexporter.cpp
Updated guide of create_plugin script
Fixed bug - checking bad pointer with return value
=> Flow meter fixes

flow_meter/pstatsplugin.h
Re-add deleted line in IPFIX export
=> fixed IPFIX emelent size

.travis.yml, configure.ac, debug_sender/debug_sender.py, device_classifier/libsvm/tools/easy.py, device_classifier/libsvm/tools/measure.py, device_classifier/libsvm/tools/trans_class.py
Python2 dependency is removed. Python scripts was converted by Automated Python 2 to 3 code translation (2to3).
=> Removed python2 support

link_traffic/munin/link_traffic_
Append Total row to the list of links with a sum per direction in munin graph.
=> link_traffic: add Total counter

Makefile.am, backscatter/EventTracker.cpp, backscatter/EventTracker.h, backscatter/FeatureVector.cpp, backscatter/FeatureVector.h, backscatter/Makefile.am, backscatter/README.md, backscatter/backscatter.cpp, backscatter/backscatter.h, backscatter/backscatter.sup, backscatter/backscatter_common.cpp, backscatter/backscatter_common.h, configure.ac, nemea-modules.spec.in
New NEMEA module for feature extraction from backscatter like traffic
=> Backscatter

scalar-aggregator/aggregator.c, scalar-aggregator/timedb.c
=> Scalar aggregator fixes

ChangeLog, NEWS, configure.ac, nemea-modules.spec.in, unirecfilter/lib/Makefile.am
* removed *.la files
* disabled automatic setting of hardening flags
=> RPM: fix build for Fedora 36+
