CESNET/Nemea-Modules

- logreplay/logreplay.cpp
Issue was requested by Dominik Soukup who uses logreplay for SIOT testing.
Currently, when `time` column is detected, `logreplay` should compute time difference and wait before sending new UniRec message.
> Logreplay delaying

- email_reporter/email_reporter.py
The sort invocation has been tested in Python 2 and 3.
> email_reporter: Sort field names from longest to shortest.

- unirecfilter/README.md
- unirecfilter/lib/functions.c
- unirecfilter/lib/functions.h
- unirecfilter/lib/parser.y
- unirecfilter/lib/scanner.l
From now, UniRec time fields can be compared with date&time constants.
This PR also contains some bugfixes.
> Improvement of unirecfilter: ur_time_t fields comparison

- aggregator/aggregator.cpp
Hotfix: Using of incorrect ur_template. 
In init_record() function when ur_clear_varlen() called, incorrect ur_template passed to function which could cause segmentation fault. Now using the right one suitable for the created record.
> Hotfix: Using of incorrect UniRec template in framework function.

- logreplay/logreplay.cpp
Logreplay did not properly terminate if there was connected a client
which was not receiving. The behavior was changed to:
First SIGINT: attempt to break the main loop and send EOF message to the connected client.
Second SIGINT: forcefully terminate libtrap and thus don't send EOF message to the connected client (useful if the client is not responding).
> logreplay: fixed bug when logreplay did not terminate

- report2idea/sipbruteforce/sipbf2idea.py
This PR is a recreated one - the original PR was split into two.
According to the feedback by Pavel Kacha, we should put a fixed string into `Description`, variable string might be in `Note`.
This patch fixes the issue for sipbf2idea.
> sipbf2idea: changed Description and SIP URI moved into Note

- logger/Makefile.am
- topn/Makefile.am
ccache fails on C99 construct by default (tested on Fedora29, ccache
3.4.2, during compilation of Turris Omnia packages).
That's why we should specify right standard for modules that use
features like:
```
for (int i = 0; i < size; i++) {
```
if we want to compile them on multiple platforms.
> build: update Makefile.am for logger&topn - enforce C std

- prefix_tags/Makefile.am
Bugfix: Fix failed compilation of `test_prefix_tags` due to missing `libtrap` linker dependency.
This adds `-ltrap` to the `test_prefix_tags_LDADD` environmental variable in `prefix_tags/Makefile.am`, which is needed by `ur_set_output_template(ifc, tmplt)` defined in `#include <unirec/unirec.h>`.
Without the `libtrap`, the linking fails with the following output:
```
CCLD     prefix_tags
prefix_tags_functions.o: In function `update_output_format':
/home/paulos/sources/Nemea-Modules/prefix_tags/prefix_tags_functions.c:33: undefined reference to `trap_get_global_ctx'
//usr/local/lib/libunirec.a(libunirec_la-unirec.o): In function `ur_ctx_set_output_template':
/home/paulos/sources/Nemea-Framework/unirec/unirec.c:786: undefined reference to `trap_ctx_set_data_fmt' …
```
> prefix_tags: add libtrap as a linker dependency

- configure.ac
- nemea-modules.spec.in
- report2idea/Makefile.am
- report2idea/warden_filer/Makefile.am
- report2idea/warden_filer/nemea_warden_filer
Add new shell script - a wrapper for warden_filer so we can use
namespace configured in the common configuration file of reporter
modules.
The script (nemea_warden_filer) rewrites `Name` and `name` in the given
warden_client configuration file and executes warden_filer.py as a
sender.
> report2idea: warden_filer wrapper

- report2idea/blacklist/blacklist2idea.py
* In 3c7ebb2e2ad34889a0d49e9949f58825b572f618 a hotfix was created
for nonvalid blacklist hostname and URL representation. The condition
used there was (x is not None and len(x)), which is equivalent
to (x) as both None and iterable of length 0 are treated as False.
The simplified condition works exactly the same in these cases. There
still remains the case of non-iterables, where the code will fail
(as list cannot be constructed from non-iterables), but the previous
would also. To be extra safe there, one should do like
try: y = list(x); except TypeError: y = list(); but according to [1],
xml.etree.ElementTree.parse() should return ElementTree instance which
should only evaluate to iterable or None when passed to list constructor,
so y = list(x) if (x) else list(); is probably enough. …
> blacklist2idea: Simplify the nonvalid XML condition

- .travis.yml
- configure.ac
- unirecfilter/README.md
- unirecfilter/lib/Makefile.am
- unirecfilter/lib/functions.c
- unirecfilter/lib/functions.h
- unirecfilter/lib/parser.y
- unirecfilter/lib/scanner.l
- unirecfilter/lib/test_liburfilter.c
This is a draft of an extension of liburfilter to support optimized
filtering of integer values like this:
`DST_PORT in [1, 234, 123, 80, 443]`
The array (in brackets `[` and `]`)is parsed, sorted, and finnaly in
evalAST() searched using bsearch().
This should be faster than complicated filter like this:
`DST_PORT == 1 or DST_PORT == 234 or DST_PORT == 123 or DST_PORT == 80 or DST_PORT == 443`
Note: this patch also adds a basic test in cmocka. To run it,
libcmocka-devel (or equivalent) must be installed.
The patch should be improved:
* distinguish signed / unsigned numbers (right now everything is
compared as uint64_t)
* add missing UniRec types like ipaddr, macaddr, time
> unirecfilter: "In Array" feature

- flow_meter/Makefile.am
- flow_meter/byte-utils.h
- flow_meter/ipfixexporter.cpp
- flow_meter/pstatsplugin.h
The previous implementation used the wrong format of IPDIX datatype "dateTimeMilliseconds". This PR fixed the issue.
> Pstat plugin IPFIX export fixed

- flow_meter/pcapreader.cpp
Bad conversion of nanoseconds from NDP caused malformed timestamps.
> flow_meter: ndp: bugfix bad conversion of nanoseconds

- flow_meter/create_plugin.sh
- flow_meter/flow_meter.cpp
ipfixprobe and flow_meter had separated lists of supported plugins. This PR defines a single macro that is contained in both help strings.
> flow_meter: MAINTENANCE deduplicate list of supported plugins

- flow_meter/ssdpplugin.cpp
- flow_meter/ssdpplugin.h
Bugfixes:
- Misinterpreted return value -1 as unsigned 65535 when parsing of location port failed - fixed in `parse_loc_port()` rework.
- SSDP_NT and SSDP_ST fields could be longer then 255 characters, but the ipfix export didn't properly account for this. -fixed
- The newline sequence used in SSDP `\r\n` was not being entirely removed. - fixed
Additions:
- SSDP plugin now has stats.
Codestyle: whitespace changes were made to suit the codestyle.
> flow_meter: ssdp plugin patch

- flow_meter/pcapreader.cpp
Flow_meter cannot be compiled on MIPS big endian arch due to missing op_len1 and op_len2 in TRILL header structure.
> flow_meter: BUGFIX inconsistent TRILL struct for BIG_ENDIAN

- flow_meter/nfbCInterface/ndpreader.cpp
- flow_meter/nhtflowcache.cpp
- flow_meter/nhtflowcache.h
Changed flowcache timeout handling and added sleep to NdpReader when no packets are read. This fix problem with high cpu usage when reading packets using ndp.
> flow_meter: fix high cpu usage while using ndp

- aggregator/agg_functions.cpp
- aggregator/agg_functions.h
- aggregator/aggregator.cpp
- aggregator/configuration.cpp
- aggregator/configuration.h
- aggregator/key.h
- nemea-modules.spec.in
The new option of aggregation function allows us to choose first non-empty (or non-zero) value of the field. In practice, it checks if the size of the currently stored variable-length field is 0 or if the fixed-sized field is equal to zero.
This feature is useful, e.g., to pair flow records from several flow_meter plugins.
> aggregator: "first non-empty" feature

- nfreader/nfdump_reader.c
An infinite loop occurs if the last record does not match the filter.
The **lnf_read** function does not modify the **recp** parameter, so it remains on the last record.
Thanks to xmarus07 for the notification.
> nfreader: bugfix infinite loop

- json_dump/json_dump.py
A message is printed to stdout when the "end-of-stream" message is received (only when verbose mode is enabled). I just used it to debug another module sending EOS non-intentionally - it can be useful in other cases as well.
> json_dump: added verbose print about end-of-stream msg

- json_replay/README.md
Missing '<' in usage examples. Module needs data to stdin, current example is not working.
> README example fix

- configure.ac
- unirecfilter/Makefile.am
- unirecfilter/README.md
- unirecfilter/lib/functions.c
- unirecfilter/lib/functions.h
- unirecfilter/lib/parser.y
- unirecfilter/lib/scanner.l
- unirecfilter/test/Makefile.am
- unirecfilter/test/integration-test.py
This PR fixes an issue discovered by GCC (float vs. double) and adds new features regarding `host`/`port` keywords that can be used in expressions including IN ARRAY feature. IN ARRAY feature was enhanced to support IP prefixes.
> unirecfilter: keyword feature

- prefix_tags/prefix_tags_functions.c
There is already `ur_copy_fields()` that should copy everything. The only important thing is to allocate enough memory -> space for message is set to max size.
> prefix_tags: remove error on variable length fields, just copy them

- device_classifier/libsvm/tools/binary.py.in
`rpmbuild` automatically scans all the files aimed to contain into the package and extracts all requirements.
Since there was a python script with `/usr/bin/python2` shebang, it caused the resulting RPM gained dependency on python2 (which is not a wished state).
PR contains a patch to update the python script from libsvm to get rid of python2.
> device_classifier: minor changes to get rid of python2

- unirecfilter/unirecfilter.c
When filters are read from file (using -f parameter), the file also contains specification of the set of fields on each output. The -O parameter is overridden/ignored in such case.
This change adds a warning to notify user that the passed -O parameter has no effect.
> unirecfilter: Print warning when using -O with -f

- anonymizer/README
- anonymizer/anonymizer.c
Two optional parameters were added to skip anonymization of SRC_IP (option -S) or DST_IP (option -D).
Example to leave SRC_IP without any modification:
/usr/bin/nemea/anonymizer -i u:input,u:output -S
Example to leave both SRC_IP and DST_IP without any modification: /usr/bin/nemea/anonymizer -i u:input,u:output -S -D
> anonymizer: option to skip SRC_IP (-S)/DST_IP (-D)

- unirec2json/unirec2json.py
apply_mapping() is called only when a -M parameter was provided.
> unirec2json: bugfix failure if -M is missing
